// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP20Ex03FW3Br7EgzcTKG4LA--sxdI3Vg',
    appId: '1:601705661315:web:3dfa99d0e41cd1cb776cb6',
    messagingSenderId: '601705661315',
    projectId: 'calopulse',
    authDomain: 'calopulse.firebaseapp.com',
    storageBucket: 'calopulse.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHUf4q-BYMemjxzf-gY5fXh6si-O1N3VA',
    appId: '1:601705661315:android:9db88f0bff11b064776cb6',
    messagingSenderId: '601705661315',
    projectId: 'calopulse',
    storageBucket: 'calopulse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTG9r61IVNBTY05ywZisQi1jD3vf1g8BM',
    appId: '1:601705661315:ios:1f2823508d070f3b776cb6',
    messagingSenderId: '601705661315',
    projectId: 'calopulse',
    storageBucket: 'calopulse.firebasestorage.app',
    iosBundleId: 'com.example.caloPulse',
  );
}
